"use client";

import LearnSidebar from "@/components/learn-sidebar";

export default function MultiAgentSystems() {
  return (
    <div className="flex py-0 px-0">
      <div className="fixed top-28 left-0 w-72 h-[calc(100vh-7rem)] z-20">
        <LearnSidebar />
      </div>
      <main className="flex-1 pl-8 max-w-3xl ml-72">
        <h1 className="text-3xl font-bold mb-4 text-pink-600">Multi Agent Systems</h1>
        <div className="text-sm text-muted-foreground mb-6"></div>
        <p className="mb-4">A multi-agent system (MAS) consists of multiple artificial intelligence (AI) agents working collectively to perform tasks on behalf of a user or another system.</p>
        <p className="mb-4">Each agent within a MAS has individual properties but all agents behave collaboratively to lead to desired global properties. Multi-agent systems are valuable in completing large-scale, complex tasks that can encompass hundreds, if not thousands, of agents.</p>
        <p className="mb-4">Central to this idea are artificial intelligence (AI) agents. An AI agent refers to a system or program capable of autonomously performing tasks on behalf of a user or another system by designing its workflow and using available tools. At the core of AI agents are large language models (LLMs). These intelligent agents leverage the advanced natural language processing techniques of LLMs to comprehend and respond to user inputs. Agents work through problems step-by-step and determine when to call on external tools. What differentiates AI agents from traditional LLMs is the use of tools and the ability to design a plan of action. The tools available to an agent can include external datasets, web searches and application programming interfaces (APIs). Similarly to human decision-making, AI agents can also update their memory as they acquire new information. The information-sharing, tool usage and adaptive learning allow AI agents to be more general purpose than traditional LLMs.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Single agent versus multi-agent systems</h2>
        <p className="mb-4">Single agent intelligent systems engage with their environment to autonomously plan, call tools and produce responses. The tools made available to an agent provide information that is otherwise unavailable to the agent. As previously described, this information can be a database acquired through an API or another agent. There is a distinction here between single and multi-agent systems. When calling another agent as a tool, that secondary agent is part of the original agent’s environmental stimuli. That information is acquired and no further cooperation takes place. Whereas multi-agent systems differ by involving all agents within the environment to model each other’s goals, memory and plan of action. Communication between agents can be direct or indirect through altering the shared environment.</p>
        <p className="mb-4">Each entity within a multi-agent system is an autonomous agent to some extent. This autonomy is typically seen by the agent’s planning, tool calling and general reasoning. In a multi-agent system, agents remain autonomous but also cooperate and coordinate in agent structures. To solve complex problems, agent communication and distributed problem-solving are key. This type of agent interaction can be described as multi-agent reinforcement learning. The information shared through this form of learning can include instantaneous information acquired through sensors or actions. Additionally, an agent’s experiences in the form of episodic information can be shared. These episodes can be sequences of sensations, actions and learned policies. Finally, agents can share their experiences in real-time to prevent other agents from repetitively learning the same policies.</p>
        <p className="mb-4">Individual agents are powerful on their own. They can create subtasks, use tools and learn through their interactions. The collective behavior of multi-agent systems increases the potential for accuracy, adaptability and scalability. Multi-agent systems tend to outperform single-agent systems due to the larger pool of shared resources, optimization and automation. Instead of multiple agents learning the same policies, one can share learned experiences to optimize time complexity and efficiency.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Architectures of multi-agent systems</h2>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Centralized networks</h3>
        <p className="mb-4">Multi-agent systems can operate under various architectures. In centralized networks, a central unit contains the global knowledge base, connects the agents and oversees their information. A strength of this structure is the ease of communication between agents and uniform knowledge. A weakness of the centrality is the dependence on the central unit; if it fails, the entire system of agents fails.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Decentralized networks</h3>
        <p className="mb-4">Agents in decentralized networks share information with their neighboring agents instead of a global knowledge base. Some benefits of decentralized networks are robustness and modularity. The failure of one agent does not cause the overall system to fail since there is no central unit. One challenge of decentralized agents is coordinating their behavior to benefit other cooperating agents.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Structures of multi-agent systems</h2>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Hierarchical structure</h3>
        <p className="mb-4">A hierarchical structure is tree-like and contains agents with varying levels of autonomy. Within a simple hierarchical structure, one agent can have the decision-making authority. In a uniform hierarchical structure, the responsibility can be distributed among multiple agents.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Holonic structure</h3>
        <p className="mb-4">Within this architecture type, agents are grouped into holarchies. A holon is an entity that cannot operate without its components. For instance, the human body is a holon because it cannot function without working organs. Similarly, in holonic multi-agent systems, the leading agent can have multiple subagents while appearing to be a singular entity. These subagents can also play roles in other holons. These hierarchical structures are self-organized and created to achieve a goal through the collaboration of the subagents.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Coalition structure</h3>
        <p className="mb-4">Coalitions are helpful in cases of underperforming singular agents in a group. In these situations, agents temporarily unite to boost utility or performance. Once the desired performance is reached, the coalitions are disbursed. It can become difficult to maintain these coalitions in dynamic environments. Regrouping is often necessary to enhance performance.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Teams</h3>
        <p className="mb-4">Teams are similar in structure to coalitions. In teams, agents cooperate to improve the performance of the group. Agents in teams do not work independently, unlike in coalitions. Agents in teams are much more dependent on one another and their structure is more hierarchical than coalitions.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Behaviors of multi-agent systems</h2>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Flocking</h3>
        <p className="mb-4">The collective behavior seen in multi-agent systems can resemble that of birds, fish and humans. In these systems, agents share an objective and require some organization to coordinate their behavior. Flocking pertains to directional synchronization and the structure of these flocks can be described by these heuristics:</p>
        <ul className="mb-4 list-disc list-inside pl-4">
          <li>Separation: attempt to avoid collision with nearby agents.</li>
          <li>Alignment: attempt to match the velocity of nearby agents.</li>
          <li>Cohesion: attempt to remain close to other agents.</li>
        </ul>
        <p className="mb-4">In the context of software agents, this coordination is crucial for multi-agent systems managing transportation networks such as railroad systems.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Swarming</h3>
        <p className="mb-4">The spatial positioning of agents in a multi-agent system can be compared to the swarming that occurs in nature. For instance, birds fly in sync by adjusting to neighboring birds. From a technical perspective, swarming is the emergent self-organization and aggregation among software agents with decentralized control. A benefit of swarming is that one operator can be trained to manage a swarm of agents. This method is less computationally expensive and more reliable than training an operator for each agent.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Use cases of multi-agent systems</h2>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Transportation</h3>
        <p className="mb-4">Multi-agent systems can be used to manage transportation systems. The qualities of multi-agent systems that allow for the coordination of complex transportation systems are communication, collaboration, planning and real-time information access. Examples of distributed systems that might benefit from MAS are railroad systems, truck assignments and marine vessels visiting the same ports.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Healthcare and public health</h3>
        <p className="mb-4">Multi-agent systems can be used for various specific tasks in the healthcare field. These agent-based systems can aid in disease prediction and prevention through genetic analysis. Medical research about cancer might be one application. In addition, multi-agent systems can serve as tools for preventing and simulating epidemic spread. This forecasting is made possible by using epidemiologically informed neural networks and machine learning (ML) techniques to manage large datasets. These findings can affect public health and public policy.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Supply chain management</h3>
        <p className="mb-4">Numerous factors affect a supply chain. These factors range from the creation of goods to the consumer purchase. Multi-agent systems can use their vast informational resources, versatility and scalability to connect the components of supply chain management. To best navigate this intelligent automation, virtual agents should negotiate with one another. This negotiation is important for agents collaborating with other agents that have conflicting goals.</p>
        <h3 className="text-xl font-semibold mt-8 mb-2 text-emerald-600">Defense systems</h3>
        <p className="mb-4">Multi-agent systems can aid in strengthening defense systems. Potential threats can include both physical national security issues and cyberattacks. Multi-agent systems can use their tools to simulate potential attacks. One example is a maritime attack simulation. This scenario would involve agents working in teams to capture the interactions between encroaching terrorist boats and defense vessels. Also, by working in cooperative teams, agents can monitor different areas of the network to detect incoming threats such as distributed denial of service (DDoS) flooding attacks.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Advantages of multi-agent systems</h2>
        <ul className="mb-4 list-disc list-inside pl-4">
          <li><b>Flexibility:</b> Multi-agent systems can adjust to varying environments by adding, removing or adapting agents.</li>
          <li><b>Scalability:</b> The cooperation of several agents allows for a greater pool of shared information. This collaboration allows multi-agent systems to solve more complex problems and tasks than single-agent systems.</li>
          <li><b>Domain specialization:</b> Single agent systems require one agent to perform tasks in various domains, whereas each agent in a multi-agent system can hold specific domain expertise.</li>
          <li><b>Greater performance:</b> Multi-agent frameworks tend to outperform singular agents. This is because the more action plans are available to an agent, the more learning and reflection occur. An AI agent incorporating knowledge and feedback from other AI agents with specialties in related areas can be useful for information synthesis. This backend collaboration of AI agents and the ability to fill information gaps are unique to agentic frameworks, making them a powerful tool and a meaningful advancement in artificial intelligence.</li>
        </ul>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Challenges of multi-agent systems</h2>
        <ul className="mb-4 list-disc list-inside pl-4">
          <li><b>Agent malfunctions:</b> Multi-agent systems built on the same foundation models can experience shared pitfalls. Such weaknesses might cause a system-wide failure of all involved agents or expose vulnerability to adverse attacks. This highlights the importance of data governance in building foundation models and the need for thorough training and testing processes.</li>
          <li><b>Coordination complexity:</b> One of the greatest challenges with building multi-agent systems is developing agents that can coordinate and negotiate with one another. This cooperation is essential for a functioning multi-agent system.</li>
          <li><b>Unpredictable behavior:</b> The agents performing autonomously and independently in decentralized networks can experience conflicting or unpredictable behavior. Detecting and managing issues within the larger system might be difficult under these conditions.</li>
        </ul>
      </main>
    </div>
  );
}
