"use client";

import LearnSidebar from "@/components/learn-sidebar";

export default function Protocols() {
  return (
    <div className="flex py-0 px-0">
      <div className="fixed top-28 left-0 w-72 h-[calc(100vh-7rem)] z-20">
        <LearnSidebar />
      </div>
      <main className="flex-1 pl-8 max-w-3xl ml-72">
        <h1 className="text-3xl font-bold mb-4 text-pink-600">Protocols</h1>
        <div className="text-sm text-muted-foreground mb-6"></div>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Agent Communication Protocol (ACP)</h2>
        <p className="mb-4">Agent Communication Protocol (ACP)  is a foundational framework in multi-agent systems that defines the rules, structures, and semantics for how autonomous AI agents communicate and coordinate with one another. It establishes a formal method by which agents exchange information through well-defined message types and interaction patterns, ensuring that communication is clear, interpretable, and purpose-driven. One of the most widely recognized standards for ACP is defined by FIPA (Foundation for Intelligent Physical Agents), which introduces performative message types such as inform, request, agree, refuse, query, propose, and accept, each indicating the intention behind an agent’s message. For example, when an agent sends a request message, it expects the receiver to perform an action or provide a response. These structured interactions allow agents to engage in complex behaviors like negotiation, collaboration, task delegation, auctions, and conflict resolution. ACP also supports the use of interaction protocols, which are like communication blueprints or conversation rules (e.g., Contract Net Protocol, Dutch Auction Protocol), guiding how multi-step dialogs unfold between agents. In systems where agents are developed independently or use different architectures, ACP plays a vital role in enabling interoperability and standardization, ensuring agents can understand and respond to each other regardless of internal differences. This becomes particularly critical in large-scale, distributed environments like smart cities, supply chains, autonomous fleets, or decentralized networks, where multiple agents must interact reliably and make decisions collaboratively. Overall, ACP transforms a group of isolated agents into a coordinated, communicative, and intelligent collective, capable of achieving shared goals through structured, purposeful dialogue.</p>
        <h2 className="text-2xl font-semibold mt-10 mb-4 text-emerald-600">Model Context Protocol (MCP)</h2>
        <p className="mb-4">Model Context Protocol (MCP) is an emerging and advanced concept in AI agent architecture that focuses on providing a structured context-sharing mechanism between agents, especially when they operate using complex or evolving models like large language models (LLMs), decision-making trees, or reinforcement learning systems. Unlike the Agent Communication Protocol (ACP), which governs how agents talk, MCP is more concerned with what background information, assumptions, and internal state are made available during that interaction to ensure accurate, efficient, and meaningful exchanges. In essence, MCP acts like a meta-layer protocol that wraps communication with relevant contextual metadata about an agent’s knowledge base, goals, environmental variables, capabilities, or even limitations. This helps reduce ambiguity and misinterpretation between agents—something that is vital when agents are trained differently, belong to different domains, or operate in dynamic and decentralized ecosystems. For example, in a multi-agent negotiation involving weather forecasting and transportation planning, an agent adhering to MCP would not only share its prediction but also specify the confidence level, training data version, and domain assumptions used in its model. MCP enables a form of model transparency and traceability, where agents can evaluate the reliability and relevance of each other’s information based on shared context. This is especially critical in mission-critical AI systems, collaborative robotics, and explainable AI scenarios. Moreover, MCP supports interoperability between symbolic and sub-symbolic agents, bridging the gap between classic rule-based AI and newer neural models. As AI systems become more decentralized, adaptive, and autonomous, the Model Context Protocol is expected to become a key enabler for context-aware, trust-building communication, making multi-agent collaboration far more robust, reliable, and aligned with human expectations.</p>
      </main>
    </div>
  );
}
